fix

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -41,86 +41,97 @@ jobs:
           chmod 600 ${{ env.ssh_folder }}/${{ env.ssh_file }}.pub -v
         working-directory: "${{ github.workspace }}"
 
-      - name: Terraform - Format
-        id: fmt
-        run: terraform fmt -check
-        continue-on-error: true
+      - run: find
+      - run: find
+        working-directory: "${{ github.workspace }}"
 
-      - name: Terraform - Init
-        id: init
-        run: terraform init
-        continue-on-error: true
+      # - name: Terraform - Format
+      #   id: fmt
+      #   run: terraform fmt -check
+      #   continue-on-error: true
 
-      - name: Terraform - Validate
-        id: validate
-        run: terraform validate -no-color
-        continue-on-error: true
+      # - name: Terraform - Init
+      #   id: init
+      #   run: terraform init
+      #   continue-on-error: true
 
-      - name: Terraform - Plan
-        id: plan
-        # if: github.event_name == 'pull_request'
-        run: terraform plan -no-color -input=false
-        continue-on-error: true
-        working-directory: "${{ env.tf_folder }}"
+      # - name: Terraform - Validate
+      #   id: validate
+      #   run: terraform validate -no-color
+      #   continue-on-error: true
 
-      - name: Pull Request Comment
-        uses: actions/github-script@v6
-        # if: github.event_name == 'pull_request'
-        env:
-          PLAN: "${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const botComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
-            })
+      # - name: Terraform - Plan
+      #   id: plan
+      #   # if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
+      #   working-directory: "${{ env.tf_folder }}"
 
-            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
-            <details><summary>Validation Output</summary>
+      # - name: Terraform - Plan
+      #   id: plan
+      #   # if: github.event_name == 'pull_request'
+      #   run: terraform plan -no-color -input=false
+      #   continue-on-error: true
+      #   working-directory: "${{ env.tf_folder }}"
 
-            \`\`\`\n
-            ${{ steps.validate.outputs.stdout }}
-            \`\`\`
+      # - name: Pull Request Comment
+      #   uses: actions/github-script@v6
+      #   # if: github.event_name == 'pull_request'
+      #   env:
+      #     PLAN: "${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const { data: comments } = await github.rest.issues.listComments({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         issue_number: context.issue.number,
+      #       })
+      #       const botComment = comments.find(comment => {
+      #         return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
+      #       })
 
-            </details>
+      #       const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️ \`${{ steps.init.outcome }}\`
+      #       #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
+      #       <details><summary>Validation Output</summary>
 
-            #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
+      #       \`\`\`\n
+      #       ${{ steps.validate.outputs.stdout }}
+      #       \`\`\`
 
-            <details><summary>Show Plan</summary>
+      #       </details>
 
-            \`\`\`terraform\n
-            ${process.env.PLAN}
-            \`\`\`
+      #       #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
 
-            </details>`;
+      #       <details><summary>Show Plan</summary>
 
-            if (botComment) {
-              github.rest.issues.updateComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: botComment.id,
-                body: output
-              })
-            } else {
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: output
-              })
-            }
+      #       \`\`\`terraform\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
 
-      - name: Terraform Status
-        if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure'
-        run: exit 1
+      #       </details>`;
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-        run: terraform apply -auto-approve -input=false
+      #       if (botComment) {
+      #         github.rest.issues.updateComment({
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           comment_id: botComment.id,
+      #           body: output
+      #         })
+      #       } else {
+      #         github.rest.issues.createComment({
+      #           issue_number: context.issue.number,
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           body: output
+      #         })
+      #       }
+
+      # - name: Terraform Status
+      #   if: steps.plan.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure'
+      #   run: exit 1
+
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+      #   run: terraform apply -auto-approve -input=false
